### PR TITLE
Add needed ports to the Vagrantfile

### PR DESCRIPTION
**Pull request by mosheeven**
These ports are used for the docker exercise.

### CODE REVIEW

**Comment by lmilbaum** [comment]
@mosheeven Are you on our Slack channel?

**Comment by mosheeven** [comment]
No, I am not using slack, why?

**Comment by mosheeven** [comment]
What is the status for the pull request, should I add/fix something?

**Comment by lmilbaum** [comment]
I am not following. This repo consists of training resources for our workshops.  PRs are merged only to fix/update/add training resources. 
Can you provide more information on this PR?

**Pull request closed without merging**
